// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGx6Fmc2co-gYJBO2Y626MmE4VJysryRA',
    appId: '1:588156938455:web:7ada441b77b998a3736892',
    messagingSenderId: '588156938455',
    projectId: 'bluetouch-81627',
    authDomain: 'bluetouch-81627.firebaseapp.com',
    storageBucket: 'bluetouch-81627.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZgSRgVJh6POhx5rOYBu79JiUq7qmrCWY',
    appId: '1:588156938455:android:f36aaa34ccc73a12736892',
    messagingSenderId: '588156938455',
    projectId: 'bluetouch-81627',
    storageBucket: 'bluetouch-81627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDzVHmjuc63INxbR2qOAD0Lt-b-OpZpY',
    appId: '1:588156938455:ios:2deb2c9f789072de736892',
    messagingSenderId: '588156938455',
    projectId: 'bluetouch-81627',
    storageBucket: 'bluetouch-81627.appspot.com',
    androidClientId: '588156938455-0dsj1nnvptf6p4vhrt5icereus8ivs9s.apps.googleusercontent.com',
    iosClientId: '588156938455-nmflnotvmnophd1scnsk394a4o48j2s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluetouch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKDzVHmjuc63INxbR2qOAD0Lt-b-OpZpY',
    appId: '1:588156938455:ios:2deb2c9f789072de736892',
    messagingSenderId: '588156938455',
    projectId: 'bluetouch-81627',
    storageBucket: 'bluetouch-81627.appspot.com',
    androidClientId: '588156938455-0dsj1nnvptf6p4vhrt5icereus8ivs9s.apps.googleusercontent.com',
    iosClientId: '588156938455-nmflnotvmnophd1scnsk394a4o48j2s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluetouch',
  );
}
